version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
      - dependency-name: "@vercel/ncc"
        versions:
          - ">=0.43.0"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
